services:
  - type: web
    name: safepay-backend
    env: python
    buildCommand: |
      pip install -e .
      python -m pip install --upgrade pip
    startCommand: python server/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: safepay-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ML_QR_SERVICE_PORT
        value: 8000
      - key: ML_VOICE_TEXT_SERVICE_PORT
        value: 8100
      - key: ML_VIDEO_SERVICE_PORT
        value: 8200
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: safepay-db
    databaseName: safepay_db
    user: postgres
    plan: free
